/*
THESIS: CodeLab makes the experiment-to-result loop feel immediate, not intimidating.
OWN-WORLD: Soft daylight lavender or near-black focus mode, with violet action geometry and practical dark code wells.
STORY: A learner chooses a language, changes a starter, runs it, and uses the output as a clue.
FIRST VIEWPORT: A large promise sits beside a stepped edit-run-inspect model; the workspace follows directly below.
FORM: An editorial learning desk, staged around a functional two-panel code lab.
*/
"use client";
import { useCallback, useEffect, useState } from "react";
import CodeEditor from "@/components/CodeEditor";
import OutputWindow from "@/components/OutputWindow";
import LanguageSelector from "@/components/LanguageSelector";
import CustomSelect from "@/components/CustomSelect";
import { executeRustbox, type ExecutionMetrics } from "@/lib/api";
import { CODE_SNIPPETS, CODE_TEMPLATES, DEFAULT_TEMPLATE, STUDY_CASE_TEMPLATES } from "@/lib/constants";

const experiments=[{name:"Predict & Verify",tagline:"Practice 01",instruction:"Change a number or message, then state your prediction before you run it."},{name:"Personalize Output",tagline:"Practice 02",instruction:"Make the program print your name and spot what is data versus logic."},{name:"Diagnose Faults",tagline:"Practice 03",instruction:"Run the intentional typo and use the error message as your next clue."}];
const flow=["Edit a small idea","Run the program","Read the result","Try the next move"];
const names=(payload:unknown):string[]=>{const record=typeof payload==="object"&&payload!==null?payload as Record<string,unknown>:{};const list=Array.isArray(payload)?payload:Array.isArray(record.languages)?record.languages:[];return list.map((item)=>{if(typeof item==="string")return item;if(!item||typeof item!=="object")return "";const value=item as Record<string,unknown>;const name=value.name||value.language||value.id;return typeof name==="string"?typeof value.version==="string"?`${name} ${value.version}`:name:""}).filter(Boolean) as string[]};

export default function Home(){
 const [theme,setTheme]=useState<"light"|"dark">("light"); const [language,setLanguage]=useState("javascript"); const [template,setTemplate]=useState(DEFAULT_TEMPLATE); const [code,setCode]=useState(CODE_SNIPPETS.javascript); const [stdin,setStdin]=useState(""); const [output,setOutput]=useState<string[]>([]); const [executionMetrics,setExecutionMetrics]=useState<ExecutionMetrics>(); const [htmlContent,setHtmlContent]=useState<string|null>(null); const [isLoading,setIsLoading]=useState(false); const [isChecking,setIsChecking]=useState(false); const [supported,setSupported]=useState<string[]>([]); const [languageError,setLanguageError]=useState(""); const [showSupported,setShowSupported]=useState(false); const [activeExperiment,setActiveExperiment]=useState(0); const [maximized,setMaximized]=useState(false);
 useEffect(()=>{const saved=window.localStorage.getItem("codelab-theme");if(saved==="dark"||saved==="light")setTheme(saved)},[]); useEffect(()=>{document.documentElement.dataset.theme=theme;window.localStorage.setItem("codelab-theme",theme)},[theme]);
 const load=useCallback((nextLanguage:string,nextTemplate:string)=>{const next=CODE_TEMPLATES[nextLanguage]?.[nextTemplate]||CODE_TEMPLATES[nextLanguage]?.[DEFAULT_TEMPLATE];setTemplate(nextTemplate);setCode(next?.code||"");setStdin(next?.stdin||"");setOutput([]);setExecutionMetrics(undefined);setHtmlContent(null)},[]);
 const changeLanguage=(next:string)=>{setLanguage(next);load(next,DEFAULT_TEMPLATE)};
 const applyPractice=useCallback((index:number)=>{setActiveExperiment(index);const item=STUDY_CASE_TEMPLATES[index]?.[language]||STUDY_CASE_TEMPLATES[index]?.javascript;if(item){setCode(item.code);setStdin(item.stdin);setOutput([]);setExecutionMetrics(undefined);setHtmlContent(null)};document.getElementById("studio")?.scrollIntoView({behavior:"smooth"})},[language]);
 const run=useCallback(async()=>{if(isLoading)return;setOutput([]);setExecutionMetrics(undefined);setHtmlContent(null);setIsLoading(true);try{if(language==="html"){const serialized=JSON.stringify(stdin).replace(/</g,"\\u003c");setHtmlContent(`<script>window.STDIN = ${serialized};<\/script>${code}`)}else{const result=await executeRustbox(language,code,stdin);setOutput(result.output);setExecutionMetrics(result.metrics)}}catch(error){setOutput([`Error: ${error instanceof Error?error.message:"Execution failed"}`])}finally{setIsLoading(false)}},[code,isLoading,language,stdin]);
 useEffect(()=>{const listener=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key==="Enter"){event.preventDefault();run()}if(event.key==="Escape")setMaximized(false)};window.addEventListener("keydown",listener);return()=>window.removeEventListener("keydown",listener)},[run]);
 const check=async()=>{if(supported.length){setShowSupported((visible)=>!visible);return}setIsChecking(true);setLanguageError("");try{const response=await fetch("/api/languages",{cache:"no-store"});const result:unknown=await response.json();if(!response.ok)throw new Error(typeof result==="object"&&result!==null&&"error" in result?String(result.error):"Could not check available languages.");setSupported(names(result));setShowSupported(true)}catch(error){setLanguageError(error instanceof Error?error.message:"Could not check available languages.");setShowSupported(true)}finally{setIsChecking(false)}};
 const hasResponse=output.length>0||Boolean(htmlContent); const templateOptions=Object.entries(CODE_TEMPLATES[language]||{}).map(([value,item])=>({value,label:item.name})); const practiceOptions=experiments.map((item,index)=>({value:index,label:item.name,detail:item.tagline}));
 return <main className="app-shell"><div className="shell-width"><header className="site-header"><a className="brand" href="#top"><span className="brand-mark">›_</span><span>CodeLab</span><span className="brand-note">a space for first experiments</span></a><button type="button" className="theme-toggle" onClick={()=>setTheme(theme==="light"?"dark":"light")} aria-label={`Switch to ${theme==="light"?"dark":"light"} mode`}>{theme==="light"?"☾":"☀"} <span>{theme==="light"?"Dark focus":"Light desk"}</span></button></header></div>
 <section className="hero" id="top"><div className="shell-width hero-grid"><div><p className="eyebrow">A small lab for big ideas</p><h1>Run a thought.<br/>Learn from the result.</h1><p className="hero-copy">A beginner-friendly space for turning a line of code into something you can see, question, and improve.</p><div className="hero-actions"><button type="button" className="run-button" onClick={()=>document.getElementById("studio")?.scrollIntoView({behavior:"smooth"})}>Open the code lab <span aria-hidden="true">↓</span></button><span className="hero-hint">No setup. Start with a working example.</span></div></div><aside className="story-board" aria-label="Your learning loop"><div className="story-meta"><span>YOUR LEARNING LOOP</span><span>01 — 04</span></div><div className="flow-stack">{flow.map((item,index)=><div className="flow-row" key={item}><span className="flow-number">0{index+1}</span>{item}</div>)}</div></aside></div></section>
 <section className="studio-section" id="studio"><div className="shell-width"><div className="section-intro"><div><p className="eyebrow">The workbench</p><h2>Make the next line feel possible.</h2></div><p>Choose a starter, make one change, and use the result to decide what to try next.</p></div><div className="control-deck"><div className="control-field"><label htmlFor="language-select">Language</label><LanguageSelector language={language} onSelect={changeLanguage}/></div><div className="control-field"><label htmlFor="template-select">Starter</label><CustomSelect id="template-select" value={template} options={templateOptions} onChange={(value)=>load(language,value)} /></div><div className="control-field"><label htmlFor="goal-select">Learning practice</label><CustomSelect id="goal-select" value={activeExperiment} options={practiceOptions} onChange={(value)=>applyPractice(Number(value))} /></div><div className="tool-actions"><button type="button" className="quiet-button" onClick={()=>load(language,template)}>Reset</button><button type="button" className="run-button" onClick={run} disabled={isLoading}>{isLoading?"Running…":hasResponse?"Run again":"Run code"}</button></div></div><button type="button" className="support-link" onClick={check} disabled={isChecking} aria-expanded={showSupported}>{isChecking?"Checking runtimes…":showSupported?"Hide supported runtimes":"Check supported runtimes"}</button>{showSupported&&<div className="language-drawer"><div className="drawer-title"><span>Available backend runtimes</span>{!languageError&&<span className="drawer-subtle">{supported.length} found</span>}</div>{languageError?<p className="error-text">{languageError}</p>:<div className="language-list">{supported.length?supported.map((item)=><span key={item}>{item}</span>):<span>Waiting for runtime list…</span>}</div>}</div>}{STUDY_CASE_TEMPLATES[activeExperiment]?.[language]&&<div className="challenge-banner"><div><strong>{experiments[activeExperiment].tagline}:</strong> {STUDY_CASE_TEMPLATES[activeExperiment][language].instruction}</div><span className="challenge-tag">Active practice</span></div>}<div className={`workbench ${maximized?"maximized":""}`}><CodeEditor language={language} value={code} onChange={(value)=>setCode(value||"")} stdin={stdin} onStdinChange={setStdin} onRunCode={run} isMaximized={maximized} onToggleMaximize={()=>setMaximized((value)=>!value)} height="560px"/>{!maximized&&<OutputWindow output={output} executionMetrics={executionMetrics} htmlContent={htmlContent} isLoading={isLoading} height="560px"/>}</div></div></section>
 <section className="learn-section"><div className="shell-width"><div className="learn-header"><div><p className="eyebrow">Build a learning habit</p><h2>Every execution is feedback.</h2></div><p>Use a short practice when you are not sure what to change next.</p></div><div className="experiment-list">{experiments.map((item,index)=><button type="button" className={`experiment ${activeExperiment===index?"active":""}`} key={item.name} onClick={()=>applyPractice(index)}><div className="experiment-top"><span>{item.tagline}</span>{activeExperiment===index&&<span className="experiment-dot"/>}</div><h3>{item.name}</h3><p>{item.instruction}</p><span className="experiment-action">Use this practice <span aria-hidden="true">→</span></span></button>)}</div></div></section>
 <footer className="site-footer"><div className="shell-width footer-content"><span><strong>CodeLab</strong> · a beginning-friendly code runner</span><span>Ctrl / ⌘ + Enter runs your program</span></div></footer></main>;
}